docs: update proxy-cache.md for incorrect language
apache/apisix pull request #10183
Opened 2023-09-10 08:41 UTC by AllenFang

### Description

Just update the `proxy-cache.md` for unexpected mandarin comment in EN doc

Fixes # (issue)

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2023-09-11 09:46 UTC, kayx23 requested changes

2023-09-11 09:46 UTC, kayx23 commented on docs/en/latest/plugins/proxy-cache.md
> +    cache_ttl: 10s  # Default cache TTL
```suggestion
    cache_ttl: 10s  # default cache TTL for caching on disk
```

2023-09-17 13:18 UTC, kayx23 approved these changes

2023-09-19 07:16 UTC, monkeyDluffy6017 approved these changes

2023-09-19 07:16 UTC, merged