feat: support devcontainer
apache/apisix pull request #11765
Opened 2024-11-21 06:15 UTC by bzp2010

### Description

Add devcontainer support to the project, which is expected to cover `Linux, Windows (WSL2), macOS` OSs and the `amd64, arm64` CPU ISAs, i.e. the environments used by most developers.

Basically, the container provides an isolated environment from the host, the runtime and toolset required for APISIX development are built in the container build, they will be available out of the box and developers no longer need to build and install them on the host. Just start devcontainer, wait a few moments, and it's ready to go.

Significantly simplify the parts that may be unfamiliar to developers and just focus on writing Lua code and testcase.

In addition to this, etcd is ready, maintained by docker compose and accessible on the local loopback.

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2024-11-21 09:17 UTC, bzp2010 commented
I have tested this on `Windows WSL2 + Docker Desktop` and `macOS + OrbStack`, where macOS is an arm64 based m4 chip.
Developers don't need to make any individual adjustments to any of the above environments, they will automatically do the right thing. (e.g. Installs the arm64-based binaries)

However, I don't have a desktop system running Linux, which would require someone else to help test, but that should not be a problem.

2024-11-21 09:19 UTC, bzp2010 commented
The error in the CI is not related to this PR, it also fails on other PRs, will investigate it later.

2024-11-22 06:44 UTC, SkyeYoung commented
🆒 I will help with testing using Manjaro KDE Plasma(amd64) + Docker Engine.

2025-03-17 04:16 UTC, SkyeYoung requested changes

2025-03-17 04:16 UTC, SkyeYoung commented on .devcontainer/docker-compose.yml
> +    command: sleep infinitys
```suggestion
    command: sleep infinity
```

2025-03-20 05:09 UTC, bzp2010 commented
This PR has been renovated, where the tests can run correctly, except for a problem that needs to be solved by #12070.

2025-03-21 13:46 UTC, SkyeYoung commented
> This PR has been renovated, where the tests can run correctly, except for a problem that needs to be solved by #12070.

Looks like #12070 has been merged.

2025-03-30 13:52 UTC, bzp2010 commented
Merging the master branch to fix #12070 doesn't seem to be successful, I'll rebase and force push.

![image](https://github.com/user-attachments/assets/aa40a5fb-6842-410d-b1ed-aa1a1ac9c2e4)

2025-03-31 13:57 UTC, SkyeYoung commented
Still got some error logs:

![CleanShot 2025-03-31 at 21 56 12@2x](https://github.com/user-attachments/assets/238e868b-7803-47f7-9f4e-4e7d31a072c9)

:thinking:

2025-03-31 14:01 UTC, SkyeYoung commented on .devcontainer/Dockerfile
> +    && rm -rf /tmp/*
maybe u can use `rm -rf dir1 dir2 ...`

2025-03-31 14:03 UTC, SkyeYoung commented on .devcontainer/devcontainer.json
> +  "postCreateCommand": "bash -c 'cd /workspace && rm -rf test-nginx && git config --global --add safe.directory /workspace && git submodule update --init --recursive && git clone https://github.com/o
u can try sth like `git clone --depth 1 --single-branch --branch main`

2025-03-31 14:51 UTC, SkyeYoung commented on docs/en/latest/build-apisix-dev-environment-devcontainers.md
> +Wait some minutes, depending on the internet connection or computer performance, it may take from a few minutes to tens of minutes, you can click on the Progress Bar in the bottom right corner to vie
```suggestion
Wait some minutes, depending on the internet connection or computer performance, it may take from a few minutes to tens of minutes, you can click on the Progress Bar in the bottom right corner to view a live log where you will be able to check unusual stuck.

If you encounter any problems, you can search or ask questions in [GitHub Issues](https://github.com/apache/apisix/issues) or [GitHub Discussions](https://github.com/apache/apisix/discussions), and community members will respond as promptly as possible.
```

2025-03-31 14:51 UTC, SkyeYoung commented on docs/en/latest/build-apisix-dev-environment-devcontainers.md
> +TEST_NGINX_BINARY=openresty FLUSH_ETCD=1 prove -Itest-nginx/lib -I. -r t/admin/api.t
```suggestion
export TEST_NGINX_BINARY=openresty

# run all tests
make test

# or run a specify test case file
FLUSH_ETCD=1 prove -Itest-nginx/lib -I. -r t/admin/api.t
```

`make test` requires `TEST_NGINX_BINARY`.

2025-03-31 14:51 UTC, SkyeYoung commented on docs/en/latest/build-apisix-dev-environment-devcontainers.md
> +And, the git is already installed in the container, so you can commit a change directly there.
```suggestion
And, the `git` is already installed in the container, so you can commit a change directly there.
```

2025-05-07 06:56 UTC, Baoyuantop reviewed
Works well on my arm macOS.

2025-05-07 06:56 UTC, Baoyuantop commented on docs/en/latest/build-apisix-dev-environment-devcontainers.md
> +The following uses Visual Studio Code, which has built-in integration with Dev Containers.
Need to install the Dev Containers extension?

2025-05-17 16:35 UTC, bzp2010 commented on docs/en/latest/build-apisix-dev-environment-devcontainers.md
> +The following uses Visual Studio Code, which has built-in integration with Dev Containers.
@Baoyuantop Yes

2025-05-17 16:36 UTC, bzp2010 commented on docs/en/latest/build-apisix-dev-environment-devcontainers.md
> +The following uses Visual Studio Code, which has built-in integration with Dev Containers.
Usually, it is pre-included.

2025-05-17 16:38 UTC, bzp2010 commented
I confirmed that the test failure is not related to this PR, so maybe we can merge this PR first and continue to improve usability in subsequent PRs. This PR has been open for too long.

2025-05-17 16:42 UTC, bzp2010 commented on .devcontainer/devcontainer.json
> +  "postCreateCommand": "bash -c 'cd /workspace && rm -rf test-nginx && git config --global --add safe.directory /workspace && git submodule update --init --recursive && git clone https://github.com/o
fixed

2025-05-17 16:42 UTC, bzp2010 commented on .devcontainer/Dockerfile
> +    && rm -rf /tmp/*
fixed

2025-05-21 08:45 UTC, juzhiyuan approved these changes
I have tried locally and works well

2025-05-27 15:05 UTC, SkyeYoung approved these changes
I tried it again locally, and it is still the previous environment.

`make run` and `FLUSH_ETCD=1 prove -Itest-nginx/lib -I. -r t/admin/api.t` works.

But `make test` still have some problems.

2025-06-01 06:28 UTC, bzp2010 commented
@juzhiyuan @SkyeYoung
![image](https://github.com/user-attachments/assets/f29cab99-8a95-4e9a-a24d-a8c7f329e15b)
 
These warnings will be fixed in a later PR. I will merge this PR first.

2025-06-01 06:28 UTC, merged