fix: return ok in kafka-logger
apache/apisix pull request #2222
Opened 2020-09-14 00:42 UTC by dotSlashLu

### What this PR does / why we need it:

https://github.com/apache/apisix/blob/98da870976a4893a87b31300276c8c548dac14c0/apisix/utils/batch-processor.lua#L59 needs `ok` and `err`, but `func` in `kafka-logger` returns nil if it's ok. This behaviour causes a lot of unnecessary logs though it's actually ok:

```
2020/09/14 07:29:38 [error] 67351#0: *180881201 [lua] batch-processor.lua:61: Batch Processor[kafka logger] failed to process entries: nil, context: ngx.timer, client: 10.100.2.45, server: 0.0.0.0:443
2020/09/14 07:29:38 [error] 67351#0: *180881201 [lua] batch-processor.lua:68: Batch Processor[kafka logger] exceeded the max_retry_count[1] dropping the entries, context: ngx.timer, client: 10.100.2.45, server: 0.0.0.0:443
```

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

2020-09-15 02:47 UTC, moonming approved these changes

2020-09-16 08:41 UTC, ShiningRush commented
This bug should result in an error for each request, then test case 5 should fail, proving that the case does not cover the situation, I guess it should be caused by the short waiting time, please modify the case to cover the bug

2020-09-16 08:42 UTC, ShiningRush requested changes
This bug should result in an error for each request, then test case 5 should fail, proving that the case does not cover the situation, I guess it should be caused by the short waiting time, please modify the case to cover the bug

2020-09-17 00:09 UTC, dotSlashLu commented
@ShiningRush thanks for your guide. You are right about why the error message was missed before, such a short waiting time will cover all kinds of error messages including kafka timeout and topic missing. 

I've increased the waiting time and also the `batch_max_size`, `batch_max_size` in kafka-logger setups to expose errors more quickly if there are any. Now the reproduce is stable.

Before the change:
```
#   Failed test 'TEST 5: access - pattern "[error]" should not match any line in error.log but matches line "2020/09/17
07:59:38 [error] 2386#0: *20 [lua] batch-processor.lua:61: Batch Processor[kafka logger] failed to process entries: nil, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:1984" (req 0)
# '
#   at /usr/local/share/perl/5.28.1/Test/Nginx/Socket.pm line 1280.

#   Failed test 'TEST 5: access - pattern "[error]" should not match any line in error.log but matches line "2020/09/17
07:59:38 [error] 2386#0: *20 [lua] batch-processor.lua:68: Batch Processor[kafka logger] exceeded the max_retry_count[1] dropping the entries, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:1984" (req 0)
# '
#   at /usr/local/share/perl/5.28.1/Test/Nginx/Socket.pm line 1280.
```

2020-09-17 06:57 UTC, moonming commented
@ShiningRush please take a look, thx

2020-09-17 07:00 UTC, ShiningRush approved these changes

2020-09-17 07:17 UTC, merged