release: release 2.0 version.
apache/apisix pull request #2283
Opened 2020-09-23 09:26 UTC by moonming

https://github.com/apache/apisix/milestone/7
2.0 milestone almost finished, it’s time to start release

2020-10-19 12:42 UTC, juzhiyuan requested changes

2020-10-19 12:42 UTC, juzhiyuan commented on CHANGELOG.md
> +- :bug: **`high priority`** When the data plane receives an instruction to delete a resource(router, upstream etc.), it does not properly clean up the cache, resulting in the existing resources canno
upstream  and so on or upstream, etc.

2020-10-19 12:42 UTC, juzhiyuan commented on CHANGELOG.md
> +- return right response code when `http_to_https` enabled in redirect plugin.[#2311](https://github.com/apache/apisix/pull/2311)
correct response code

2020-10-19 12:42 UTC, juzhiyuan commented on CHANGELOG_CN.md
> +- :sunrise: **从 etcd v2 协议迁移到 v3，这是不向下兼容的修改。Apache APISIX 只支持 etcd 3.4 以及后续的版本。** [#2036](https://github.com/apache/apisix/pull/2036)
missing Apache in English version

2020-10-20 00:45 UTC, moonming commented
@juzhiyuan fixed, please take a look

2020-10-20 01:02 UTC, juzhiyuan approved these changes
LGTM

2020-10-20 06:51 UTC, membphis approved these changes

2020-10-27 02:11 UTC, merged