fix(basic-auth): split schema to adapt different occasions
apache/apisix pull request #2331
Opened 2020-09-27 09:43 UTC by spacewander

### What this PR does / why we need it:

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [x] Is this PR backward compatible?

2020-09-28 01:44 UTC, liuhengloveyou commented
fix which issues?

2020-09-28 03:32 UTC, spacewander commented
The original schema check is too floppy. It will let the invalid schema in `TEST 10: invalid schema, not field given` pass, but when you hit the rule later, you will be in trouble.

2020-09-28 05:26 UTC, membphis commented
@ShiningRush I remember we discussed this method before, you can look at this PR

2020-09-28 05:27 UTC, membphis commented
this way is much better than the old way ^_^

2020-09-28 06:39 UTC, ShiningRush requested changes

2020-09-28 06:39 UTC, ShiningRush commented on apisix/core/schema.lua
> +    TYPE_ANY = 1,
- `TYPE_ANY` is confused, I think `TYPE_CONF` or `TYPE_OPT` would be better, how do you think?
- It seems like the code of checking plugin's config does not using this parameter, are there any special considerations?

2020-09-28 06:48 UTC, ShiningRush requested changes

2020-09-28 06:48 UTC, ShiningRush commented on apisix/admin/plugins.lua
> +        if type(plugin_conf) ~= "table" then
No test case cover this logic.

2020-09-28 08:52 UTC, spacewander commented on apisix/admin/plugins.lua
> +        if type(plugin_conf) ~= "table" then
@ShiningRush 
Updated.

2020-09-28 09:06 UTC, ShiningRush approved these changes

2020-09-29 00:34 UTC, moonming approved these changes

2020-10-04 06:39 UTC, merged