feat: support more customize configure in nginx.conf
apache/apisix pull request #3204
Opened 2021-01-06 09:50 UTC by shenshaoye

在使用apisix过程中由于要使用第三方模块，需要用到load_module和include这两个指令，目前关于nginx的自定义配置对这两个指令的支持有问题，因此这个pull request丰富了用户自定义配置的支持
具体见https://github.com/apache/apisix/issues/3203

2021-01-06 10:03 UTC, spacewander requested changes

2021-01-06 10:03 UTC, spacewander commented on apisix/cli/ngx_tpl.lua
> +# main start configuration snippet starts
I think we can directly move `main_configuration_snippet` here instead of creating new one?

2021-01-06 10:03 UTC, spacewander commented on .travis/apisix_cli_test/test_main.sh
> +    http_end_configuration_snippet: |
Need to check `http_end_configuration_snippet` like other snippet in the test.

2021-01-06 10:20 UTC, spacewander commented on .travis/apisix_cli_test/test_main.sh
> +grep 'server_names_hash_bucket_size 128;' -A 2 conf/nginx.conf | grep "configuration snippet ends" > /dev/null
Would be better if we also check there is a '}' in the output, like:
grep 'server_names_hash_bucket_size 128;' -A 3 conf/nginx.conf | grep "}" > /dev/null

2021-01-06 11:34 UTC, spacewander approved these changes

2021-01-06 13:53 UTC, tokers commented
@shenshaoye Should add some docs about the new adding fields.

2021-01-07 11:20 UTC, tokers approved these changes

2021-01-07 11:21 UTC, merged