feat: first attempt at APISIX overall GitHub leaderboard
apache/apisix pull request #3825
Opened 2021-03-15 05:49 UTC by jbampton

- Thought it would be good to have an AUTHORS file and I think that RAILS does it well: https://contributors.rubyonrails.org/
- Could be expanded in future to match on names too
- Was a quick Ruby script

### What this PR does / why we need it:

Shows all contributors more than 100.

### Pre-submission checklist:

* [X] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

2021-03-15 06:34 UTC, spacewander requested changes
The https://github.com/apache/apisix/graphs/contributors is good enough. There is no need to repeat it.

2021-03-15 06:36 UTC, jbampton commented
This list shows all contributors not just 100

2021-03-23 15:42 UTC, membphis commented
> The https://github.com/apache/apisix/graphs/contributors is good enough. There is no need to repeat it.

agree with this. 

The content of this page will be updated frequently later, I don't think it is necessary to maintain it specially.

2021-03-23 15:44 UTC, membphis commented
Thank you very much for your contribution. 

If the community loves this PR, please leave a message. Then we will reopen it.

2021-03-23 15:44 UTC, closed without merging