feat: allow to set custom timeout for route
apache/apisix pull request #4340
Opened 2021-05-30 10:47 UTC by yxudong

### What this PR does / why we need it:

Add optional upstream_timeout option for the route.
https://github.com/apache/apisix/issues/4258

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [x] Have you modified the corresponding document?
* [x] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

2021-05-30 22:15 UTC, Yiyiyimu commented on apisix/balancer.lua
> +    local route_conf = ctx.matched_route.value
maybe need to check if `ctx.matched_route` is nil here

2021-05-30 22:15 UTC, Yiyiyimu commented on apisix/schema_def.lua
> +        upstream_timeout = {
Just use `timeout` would seem a better name. It would override upstream timeout but it's still for routes but not upstreams

2021-05-30 22:15 UTC, Yiyiyimu commented on docs/en/latest/admin-api.md
> +| upstream_timeout | False                                    | Upstream    | Set the upstream timeout for connection, sending and receiving messages of the route. This option will overwrite the [tim
ditto and some other places. Also the type maybe should be `Auxiliary`? I'm not sure about this

2021-05-31 02:50 UTC, Yiyiyimu approved these changes

2021-05-31 03:19 UTC, spacewander requested changes

2021-05-31 03:19 UTC, spacewander commented on apisix/balancer.lua
>  local function set_balancer_opts(ctx)
We can pass route directly:
https://github.com/apache/apisix/blob/09e298302cbc8514d8240c300974746c9f85845c/apisix/balancer.lua#L247

2021-05-31 03:19 UTC, spacewander commented on apisix/schema_def.lua
> +        timeout = {
Better to exact the `timeout` to a separate schema.

2021-05-31 03:19 UTC, spacewander commented on t/admin/routes2.t
> +=== TEST 18: valid route with timeout
Need to add test to  t/node/timeout-upstream.t

2021-06-01 03:36 UTC, spacewander approved these changes

2021-06-01 05:39 UTC, tokers approved these changes

2021-06-01 05:39 UTC, merged