docs: remove wrong symbol
apache/apisix pull request #5390
Opened 2021-11-01 15:19 UTC by Xunzhuo

### What this PR does / why we need it:

docs: remove wrong symbol : "|"

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

2021-11-02 00:56 UTC, spacewander requested changes
The '|' is just an example, it can be other things.

2021-11-02 01:14 UTC, Xunzhuo commented
I know, the reason I want to remove it is that in markdown form, the '|' is a key symbol, you can see the wrong render with image before changing.
<img width="979" alt="截屏2021-11-02 上午9 13 58" src="https://user-images.githubusercontent.com/48784001/139771101-12dd069d-1481-429d-859e-844f91543087.png">
.

2021-11-02 01:19 UTC, spacewander approved these changes

2021-11-03 04:06 UTC, lilien1010 approved these changes

2021-11-03 04:34 UTC, merged