add demonstration of log config of "nginx_config" in docs.
apache/apisix pull request #6122
Opened 2022-01-16 13:56 UTC by kerneltravel

### What this PR does / why we need it:
add demonstration in log format of nginx_config customization for somebody who need an example of this subject.
and fixed the original incorrect indents.
[](https://github.com/apache/apisix/issues/6072)

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

2022-01-16 14:01 UTC, leslie-tsang commented
Hello there, Can you add a test like `fix #6072` in PR desc, it help reviewer to sync status between issues and PR.

2022-01-17 01:07 UTC, spacewander requested changes

2022-01-17 01:07 UTC, spacewander commented on docs/en/latest/customize-nginx-configuration.md
> -    main_configuration_snippet: |
I don't think the original indent (4 spaces) is wrong.

2022-01-17 01:07 UTC, closed without merging

2022-01-17 01:08 UTC, spacewander commented
There is no need to put everything into the documentation. We just document what's critical, otherwise the doc is too long to read.

2022-01-17 11:10 UTC, spacewander commented
@kerneltravel 
Anyway, I think the suggestion below is worthwhile.

> Pay attention to the indent of `nginx_config` and sub indent of the sub entries, the incorrect indent may cause `./bin/apisix start` to fail to generate Nginx configuration in `conf/nginx.conf`.

Would you mind just submitting this phrase in another PR? Thanks!