Update plugin-develop.md
apache/apisix pull request #6370
Opened 2022-02-18 06:23 UTC by shenzhuangzhi1

### What this PR does / why we need it:

Missing content in Chinese document.
### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

2022-02-20 02:48 UTC, shenzhuangzhi1 commented
what happened？

2022-02-21 01:23 UTC, tokers commented on docs/zh/latest/plugin-develop.md
> +wAPISIX提供了两种方式来添加新的功能。
```suggestion
APISIX提供了两种方式来添加新的功能。
```

2022-02-21 01:23 UTC, tokers commented on docs/zh/latest/plugin-develop.md
> +这个例子： [my_hook.lua](https://github.com/apache/apisix/blob/master/example/my_hook.lua) 可以在项目的`example`路径下被找到。
```suggestion
这个例子： [my_hook.lua](https://github.com/apache/apisix/blob/master/example/my_hook.lua) 可以在项目的`example`路径下被找到。

```

2022-02-21 04:14 UTC, tzssangglass commented on docs/zh/latest/plugin-develop.md
> +wAPISIX提供了两种方式来添加新的功能。
APISIX 提供了两种方式来添加新的功能。

2022-02-21 04:14 UTC, tzssangglass commented on docs/zh/latest/plugin-develop.md
> +此文档是关于lua语言的插件开发,其他语言请看：[external plugin](./external-plugin.md)。
```suggestion
此文档是关于 lua 语言的插件开发，其他语言请看：[external plugin](./external-plugin.md)。
```

2022-02-21 05:49 UTC, shenzhuangzhi1 reviewed
update plugin-develop.md

2022-02-21 06:35 UTC, leslie-tsang commented
Hello there, I'm afraid the syntax in the document needs to be optimized first, as the current version is a little strange.

Maybe you can refer to [copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines) to fix them.

2022-02-21 06:42 UTC, zaunist commented on docs/zh/latest/plugin-develop.md
> +APISIX提供了两种方式来添加新的功能。
```suggestion
Apache APISIX 提供了两种方式来添加新的功能。
```

2022-02-21 06:42 UTC, zaunist commented on docs/zh/latest/plugin-develop.md
> +1. 修改APISIX的源代码并重新发布 (不推荐)。
```suggestion
1. 修改 Apache APISIX 的源代码并重新发布 (不推荐)。
```
There should be a space between Chinese and English, you could ref https://github.com/sparanoid/chinese-copywriting-guidelines .

2022-02-21 15:20 UTC, tzssangglass commented on docs/zh/latest/plugin-develop.md
> +这个例子： [my_hook.lua](https://github.com/apache/apisix/blob/master/example/my_hook.lua) 可以在项目的`example`路径下被找到。
```suggestion
这个例子： [my_hook.lua](https://github.com/apache/apisix/blob/master/example/my_hook.lua) 可以在项目的 `example` 路径下被找到。
```

2022-02-22 04:59 UTC, tzssangglass submitted a review, later dismissed

2022-02-23 01:25 UTC, zaunist submitted a review, later dismissed

2022-02-23 01:57 UTC, leslie-tsang requested changes

2022-02-23 01:57 UTC, leslie-tsang commented on docs/zh/latest/plugin-develop.md
> +可能你会想覆盖一个文件中的函数，你可以在`conf/config.yaml`文件中配置`lua_module_hook` 来使你的hook生效。
```suggestion
可能你会想覆盖一个文件中的函数，你可以在 `conf/config.yaml` 文件中配置 `lua_module_hook` 来使你的 hook 生效。
```

2022-02-23 01:57 UTC, leslie-tsang commented on docs/zh/latest/plugin-develop.md
> + 当APISIX启动的时候，`example/my_hook.lua` 就会被加载，这时你可以使用这个钩子在APISIX中来全局替换掉一个方法。
```suggestion
 当 APISIX 启动的时候，`example/my_hook.lua` 就会被加载，这时你可以使用这个钩子在 APISIX 中来全局替换掉一个方法。
```

2022-02-23 01:57 UTC, leslie-tsang commented on docs/zh/latest/plugin-develop.md
> +这个例子： [my_hook.lua](https://github.com/apache/apisix/blob/master/example/my_hook.lua) 可以在项目的 `example` 路径下被找到。
```suggestion
这个例子：[my_hook.lua](https://github.com/apache/apisix/blob/master/example/my_hook.lua) 可以在项目的 `example` 路径下被找到。
```

2022-02-23 01:57 UTC, leslie-tsang commented on docs/zh/latest/plugin-develop.md
> +1. 配置  `extra_lua_path` 和 `extra_lua_cpath` 在 `conf/config.yaml`以加载你自己的代码文件。 你应该给自己的代码文件起一个不包含在原来库中的名字，而不是使用相同名称的代码文件，但是如果有需要，你可以使用这种方式覆盖内置的代码文件。
```suggestion
2. 配置 `extra_lua_path` 和 `extra_lua_cpath` 在 `conf/config.yaml` 以加载你自己的代码文件。 你应该给自己的代码文件起一个不包含在原来库中的名字，而不是使用相同名称的代码文件，但是如果有需要，你可以使用这种方式覆盖内置的代码文件。
```

2022-02-23 01:57 UTC, leslie-tsang commented on docs/zh/latest/plugin-develop.md
> +接着，在`conf/config.yaml`文件中添加如下的配置:
```suggestion
接着，在 `conf/config.yaml` 文件中添加如下的配置:
```

2022-02-23 02:21 UTC, leslie-tsang commented on docs/zh/latest/plugin-develop.md
> +1. 配置  `extra_lua_path` 和 `extra_lua_cpath` 在 `conf/config.yaml`以加载你自己的代码文件。 你应该给自己的代码文件起一个不包含在原来库中的名字，而不是使用相同名称的代码文件，但是如果有需要，你可以使用这种方式覆盖内置的代码文件。
> 你应该给自己的代码文件起一个不包含在原来库中的名字

It looks strange to me, can you try to optimize the translation?

2022-02-23 02:24 UTC, zaunist commented on docs/zh/latest/plugin-develop.md
> + 当APISIX启动的时候，`example/my_hook.lua` 就会被加载，这时你可以使用这个钩子在APISIX中来全局替换掉一个方法。
```suggestion
 当 Apache APISIX 启动的时候，`example/my_hook.lua` 就会被加载，这时你可以使用这个钩子在 Apache APISIX 中来全局替换掉一个方法。
```

2022-02-23 12:33 UTC, tzssangglass commented
Just some formatting issues

2022-02-24 01:08 UTC, zaunist commented
Could you use `Apache APISIX` instead of `APISIX` ?

2022-02-24 01:16 UTC, spacewander commented
> 

Both APISIX & Apache APISIX are OK.

2022-02-24 01:17 UTC, spacewander commented
We use APISIX directly in many places of the doc. And the original doc doesn't use Apache APISIX.

2022-02-24 01:18 UTC, zaunist commented
Got it.

2022-02-25 02:40 UTC, tzssangglass approved these changes

2022-02-25 02:50 UTC, spacewander approved these changes

2022-02-25 02:51 UTC, merged