docs: upadate Chinese installation docs
apache/apisix pull request #7002
Opened 2022-05-07 03:11 UTC by hf400159

### Description

Updated Chinese installation documentation.

Fixes # (issue)

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2022-05-07 06:09 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +title: APISIX 安装教程
```suggestion
title: APISIX 安装指南
```

2022-05-07 06:10 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +关于如何快速运行 Apache APISIX，请参考 [入门指南](./getting-started.md)。
```suggestion
关于如何快速运行 Apache APISIX，请参考[入门指南](./getting-started.md)。
```

2022-05-07 06:11 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +APISIX 使用 [etcd](https://github.com/etcd-io/etcd) 作为配置中心，来保存和同步配置。在安装 APISIX 之前，你需要在你的主机上安装 etcd。
```suggestion
APISIX 使用 [etcd](https://github.com/etcd-io/etcd) 作为配置中心进行保存和同步配置。在安装 APISIX 之前，需要在你的主机上安装 etcd。
```

2022-05-07 06:12 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +如果你在安装 APISIX 时选择 Docker 或 Hlem 安装，etcd 将会自动安装。如果你选择其他方法或者需要手动安装 APISIX，请参考以下步骤安装 etcd：
```suggestion
如果你在安装 APISIX 时选择了 Docker 或 Helm 安装，则 etcd 将会自动安装；如果你选择其他方法或者需要手动安装 APISIX，请参考以下步骤安装 etcd：
```

2022-05-07 06:14 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +下载 APISIX 离线 RPM 包到 `apisix` 文件夹：
```suggestion
将 APISIX 离线 RPM 包下载到 `apisix` 文件夹：
```

2022-05-07 06:15 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +如果你是通过其他方法安装的 APISIX，可以参考[配置文件模板](https://github.com/api7/apisix-build-tools/blob/master/usr/lib/systemd/system/apisix.service)进行修改，并将其添加在 `/usr/lib/systemd/system/apisix.service` 路径下
```suggestion
如果你是通过其他方法安装的 APISIX，可以参考[配置文件模板](https://github.com/api7/apisix-build-tools/blob/master/usr/lib/systemd/system/apisix.service)进行修改，并将其添加在 `/usr/lib/systemd/system/apisix.service` 路径下。
```

2022-05-07 06:16 UTC, SylviaBABY commented on docs/zh/latest/how-to-build.md
> +请参考[入门指南](./getting-started.md)了解如何使用 APISIX。
```suggestion
如需了解后续 APISIX 的使用，请参考[入门指南](./getting-started.md)获取更多信息。
```

2022-05-07 07:21 UTC, moonming requested changes
I think the previous directory structure is correct,  according to different installation methods such as docker, RPM, and source code.

2022-05-07 07:23 UTC, moonming reviewed
the file name is "how to build", which is means build from source code, not how to install.
And I think we can add doc for how to install.

2022-05-07 08:01 UTC, hf400159 commented
> the file name is "how to build", which is means build from source code, not how to install. And I think we can add doc for how to install.

@moonming 
1. The file name of `how-to-build` has not been changed because it is currently referenced in some documents, so it has not been changed for the time being. I will investigate and solve this problem later.
2. For the directory structure, it will be better to use the advanced features of Docusaurus to present the way, which allows the user to see the installation method he wants more intuitively.
3. For the way to build from source. We can probably move it to the GitHub repo as users installing from source would likely be checking on GitHub.
If you have other suggestions, welcome to discuss.

2022-05-07 09:36 UTC, juzhiyuan commented
> > the file name is "how to build", which is means build from source code, not how to install. And I think we can add doc for how to install.
> 
> @moonming
> 
> 1. The file name of `how-to-build` has not been changed because it is currently referenced in some documents, so it has not been changed for the time being. I will investigate and solve this problem later.
> 2. For the directory structure, it will be better to use the advanced features of Docusaurus to present the way, which allows the user to see the installation method he wants more intuitively.
> 3. For the way to build from source. We can probably move it to the GitHub repo as users installing from source would likely be checking on GitHub.
>    If you have other suggestions, welcome to discuss.

@moonming
 
1. The inconsistency between the **filename** and the** sidebar label** was a long time ago. This PR is only responsible for the internationalization and synchronization of English changes from https://github.com/apache/apisix/pull/6964;
2. The problem of inconsistency between the file name and the title should be corrected **in the new PR**. As for the historical link reference problem, @SkyeYoung could help to redirect the client to the document site to solve it. The file name can be modified to `installation.md`;
3. Building from source can be explained in a separate document (e.g., README, separate documentation for installation from source, adding **a new Tab in current page** to provide "How to build from source code").

cc @hf400159 @navendu-pottekkat @kwanhur @spacewander @SylviaBABY @yzeng25 @membphis

2022-05-07 09:39 UTC, moonming commented
> * For the directory structure, it will be better to use the advanced features of Docusaurus to present the way, which allows the user to see the installation method he wants more intuitively.

You didn't get my point. I mean, the user installs either via docker or via rpm, only one way. Therefore, the first-level directory must be the installation method.

2022-05-07 09:41 UTC, moonming commented
> * The inconsistency between the **filename** and the **sidebar label** was a long time ago. This PR is only responsible for the internationalization and synchronization of English changes from [docs: update "Installation" guide #6964](https://github.com/apache/apisix/pull/6964);

please create a issue for this, thx

2022-05-07 09:42 UTC, moonming commented
> 1. This PR is only responsible for the internationalization and synchronization of English changes from [docs: update "Installation" guide #6964](https://github.com/apache/apisix/pull/6964);

Got it. @hf400159 please add this desc in this PR, Otherwise others do not know

2022-05-07 09:44 UTC, moonming commented
> > > the file name is "how to build", which is means build from source code, not how to install. And I think we can add doc for how to install.
> > 
> > 
> > @moonming
> > 
> > 1. The file name of `how-to-build` has not been changed because it is currently referenced in some documents, so it has not been changed for the time being. I will investigate and solve this problem later.
> > 2. For the directory structure, it will be better to use the advanced features of Docusaurus to present the way, which allows the user to see the installation method he wants more intuitively.
> > 3. For the way to build from source. We can probably move it to the GitHub repo as users installing from source would likely be checking on GitHub.
> >    If you have other suggestions, welcome to discuss.
> 
> @moonming
> 
> 1. The inconsistency between the **filename** and the **sidebar label** was a long time ago. This PR is only responsible for the internationalization and synchronization of English changes from [docs: update "Installation" guide #6964](https://github.com/apache/apisix/pull/6964);
> 2. The problem of inconsistency between the file name and the title should be corrected **in the new PR**. As for the historical link reference problem, @SkyeYoung could help to redirect the client to the document site to solve it. The file name can be modified to `installation.md`;
> 3. Building from source can be explained in a separate document (e.g., README, separate documentation for installation from source, adding **a new Tab in current page** to provide "How to build from source code").
> 
> ![image](https://user-images.githubusercontent.com/2106987/167248629-53707e60-41b0-4cf2-a3f0-e63ab01d2774.png)
> 
> cc @hf400159 @navendu-pottekkat @kwanhur @spacewander @SylviaBABY @yzeng25 @membphis

![image](https://user-images.githubusercontent.com/26448043/167248875-2a49ef30-512c-4ab1-b8f4-3e48c266f368.png)
I mean we don't need to install etcd if install from docker.

2022-05-07 10:10 UTC, hf400159 commented
@juzhiyuan Since the documentation for building from source has not yet been created, there is no building from source tag added to this documentation. We will update this document later, not now. 

@moonming I will modify the content of the document so that the first level directory is the installation method.

2022-05-07 14:52 UTC, SylviaBABY approved these changes

2022-05-08 04:28 UTC, yzeng25 approved these changes

2022-05-08 11:42 UTC, moonming commented
is there a preview link for docs？

2022-05-08 11:51 UTC, SkyeYoung commented
@hf400159 Hi, we can use https://surge.sh/ to publish a preview quickly. 😊

2022-05-09 02:07 UTC, hf400159 commented
![preview](https://user-images.githubusercontent.com/97138894/167328494-8e9b799f-d097-4376-b61d-76395436c3a1.png)
@moonming I have no way to upload to suger because of my network issues. You can take a look at this screenshot.

2022-05-09 02:11 UTC, moonming commented
> @hf400159 Hi, we can use https://surge.sh/ to publish a preview quickly. 😊 (follow [README Guide](https://github.com/apache/apisix-website#basic), build, then use surge publish)

please create issue for this

2022-05-09 02:11 UTC, moonming approved these changes

2022-05-09 02:23 UTC, Baoyuantop approved these changes

2022-05-09 05:26 UTC, merged

2022-05-10 01:31 UTC, hf400159 commented
> > @hf400159 Hi, we can use https://surge.sh/ to publish a preview quickly. 😊 (follow [README Guide](https://github.com/apache/apisix-website#basic), build, then use surge publish)
> 
> please create issue for this

cc @moonming    issue link [1076]https://github.com/apache/apisix-website/issues/1076