docs: added websocket authentication
apache/apisix pull request #8462
Opened 2022-12-06 08:07 UTC by juzhiyuan

### Description

This tutorial uses `key-auth` to authenticate before connecting to the upstream WebSocket server.

Fixes # (issue)

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2022-12-07 01:48 UTC, bzp2010 reviewed
The content of the article looks good, but there is a problem here.

AFAIK, the browser's WebSocket does not provide an API to allow users to set their own initial request headers. It will affect browser users, but not users who build their own clients.

So for browsers, we'd better switch to using the query parameter as authentication to start a WS connection, otherwise it will be difficult for users to use the authentication plugin provided by APISIX in the browser.

Perhaps it would be better to provide a truly dedicated websocket plugin in the future. 😊

2022-12-07 01:48 UTC, bzp2010 commented on docs/en/latest/tutorials/websocket-authentication.md
> +![Connect with key](https://static.apiseven.com/2022/12/06/638efac7c42b6.png)
ditto

2022-12-08 04:58 UTC, navendu-pottekkat requested changes

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +**Client Request**
Would it be better to change bolds to H3 heading?

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +## WebSocket Protocol
All headings should follow sentence case as stated in the style guide: https://apisix.apache.org/docs/general/documentation-style-guide/#formatting-punctuation-and-organization

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +### Pre-requisite
```suggestion
### Prerequisites
```

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +#### Create one Route
```suggestion
#### Create a Route
```

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +#### Create one Consumer
```suggestion
#### Create a Consumer
```

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +Other authentication methods are similar to this one.
Please move this note to the top and use the Docusaurus admonition `:::note`.

2022-12-08 04:58 UTC, navendu-pottekkat commented on docs/en/latest/tutorials/websocket-authentication.md
> +1. [Wikipedia - WebSocket](https://en.wikipedia.org/wiki/WebSocket)
We do not generally have separate references section. You can just link it inline as you have done in the first sentence. We can remove this section.

2023-04-24 05:18 UTC, navendu-pottekkat commented
I will update this PR because I think @juzhiyuan is busy elsewhere.

2023-04-25 12:50 UTC, navendu-pottekkat commented
Opened new PR to add this tutorial. Closing this one.

See: https://github.com/apache/apisix/pull/9369

2023-04-25 12:50 UTC, closed without merging