feat: add opentelemetry variables
apache/apisix pull request #8834
Opened 2023-02-10 10:36 UTC by lework

### Description

Span information recorded in the access log.

Fixes #  https://github.com/apache/apisix/issues/8765

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [x] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2023-02-12 04:04 UTC, yangxikun requested changes

2023-02-12 04:04 UTC, yangxikun commented on apisix/plugins/opentelemetry.lua
> +    ngx.var.opentelemetry_span_id = span_context.span_id
We should add a bool field `set_ngx_var`(default false) in opentelemetry attr_schema, so user can enable/disable it, and keep backward compatibility.

2023-02-12 16:39 UTC, shreemaan-abhishek requested changes

2023-02-12 16:39 UTC, shreemaan-abhishek commented on docs/en/latest/plugins/opentelemetry.md
> +The following nginx variables are set by the opentelemetry:
```suggestion
The following nginx variables are set by OpenTelemetry:
```

2023-02-12 16:39 UTC, shreemaan-abhishek commented on docs/en/latest/plugins/opentelemetry.md
> +How to use variables ？you have to add it to your configuration file (`conf/config.yaml`):
```suggestion
How to use variables? You have to add it to your configuration file (`conf/config.yaml`):
```

2023-02-13 02:22 UTC, lework commented
@yangxikun @shreemaan-abhishek Thank you for the suggestion, has completed the revision.

2023-02-16 09:11 UTC, closed without merging

2023-02-16 09:32 UTC, lework commented
I synced the fork, which caused this pr to close. I brought up a new pr https://github.com/apache/apisix/pull/8871