docs : Change broken links
apache/apisix pull request #9479
Opened 2023-05-13 09:17 UTC by Arghyahub

### Description

The links in the Prerequisites section of rate limiting were broken.
![image](https://github.com/apache/apisix/assets/84245432/32e111a3-b14a-4207-aea7-0ba045fd5d2f)

This PR takes `Get APISIX` link to the correct readme page
and takes `Configure Routes` to the correct configure-routes page

Fixes #9473 

### Checklist

- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2023-05-14 12:22 UTC, juzhiyuan submitted a review, later dismissed

2023-05-14 14:44 UTC, jiangfucheng commented
@Arghyahub Hi, some links in these pages have same issues, could you fix these together?
https://apisix.apache.org/docs/apisix/getting-started/configure-routes/

2023-05-14 15:11 UTC, Gallardot submitted a review, later dismissed
LGTM! Thank you for your contribution!

2023-05-14 16:24 UTC, Arghyahub commented
> LGTM! Thank you for your contribution!

Would love to contribute more to the project💖

2023-05-14 16:25 UTC, Arghyahub commented
Sure @jiangfucheng

2023-05-14 16:45 UTC, Arghyahub commented
I have fixed all the links.
I'm new to open source and want to provide more to the community, Your guidance will help me a lot to grow in this field.
Thank you for all you help and would like to gain more experience and give back as much as I can.

2023-05-15 01:42 UTC, Gallardot requested changes
After testing, the following changes are made to adapt the document system of APISIX.

2023-05-15 01:42 UTC, Gallardot commented on docs/en/latest/getting-started/configure-routes.md
> +1. Complete [Get APISIX](./README.md) to install APISIX.
```suggestion
1. Complete [Get APISIX](../README) to install APISIX.
```

2023-05-15 01:42 UTC, Gallardot commented on docs/en/latest/getting-started/key-authentication.md
> +1. Complete [Get APISIX](./README.md) to install APISIX.
```suggestion
1. Complete [Get APISIX](../README) to install APISIX.
```

2023-05-15 01:42 UTC, Gallardot commented on docs/en/latest/getting-started/key-authentication.md
> +2. Complete [Configure Routes](./configure-routes.md).
```suggestion
2. Complete [Configure Routes](../configure-routes#what-is-a-route).
```

2023-05-15 01:42 UTC, Gallardot commented on docs/en/latest/getting-started/key-authentication.md
> +Inheriting the route `getting-started-ip` from [Configure Routes](./configure-routes.md), we only need to use the `PATCH` method to add the `key-auth` plugin to the route:
```suggestion
Inheriting the route `getting-started-ip` from [Configure Routes](../configure-routes), we only need to use the `PATCH` method to add the `key-auth` plugin to the route:
```

2023-05-15 01:42 UTC, Gallardot commented on docs/en/latest/getting-started/rate-limiting.md
> +1. Complete the [Get APISIX](./README) step to install APISIX first.
```suggestion
1. Complete the [Get APISIX](../README) step to install APISIX first.
```

2023-05-15 06:21 UTC, Arghyahub commented
Hey @Gallardot I tried putting ../ instead of ./
But the links doesn't seem to be working with that

2023-05-15 06:23 UTC, Arghyahub commented
Is there any way I can setup the frontend locally and test the site?
I have edited all files in VSCode and `./` Works for accessing files in same directory but `../` doesn't work here

2023-05-15 09:22 UTC, Gallardot commented
> Is there any way I can setup the frontend locally and test the site?
> I have edited all files in VSCode and `./` Works for accessing files in same directory but `../` doesn't work here

@Arghyahub APISIX's document repository is automatically synced to the [apisix-website](https://github.com/apache/apisix-website) project to generate documents, which you can view here https://github.com/apache/apisix-website/tree/asf-site

2023-05-15 11:31 UTC, Neilblaze commented
> ... `./` Works for accessing files in same directory but `../` doesn't work here

@Arghyahub This is because in VS code (i.e. in local) every URI in the markdown file is set at `relative path`, whereas, after deployment, it's set on `absolute` (concatenated) since it can access the directory tree of [apisix-website](https://github.com/apache/apisix-website) as previously highlighted by @Gallardot. 

Push the requested changes, we'll review them if anything goes wrong :)

2023-05-15 13:02 UTC, Arghyahub commented
Thanks @Neilblaze for guiding me😊
I'm implementing the requested changes

2023-05-16 01:42 UTC, Gallardot approved these changes

2023-05-16 09:00 UTC, monkeyDluffy6017 approved these changes

2023-05-16 09:03 UTC, Neilblaze approved these changes
LGTM! 🎉

2023-05-16 09:07 UTC, guoqqqi approved these changes

2023-05-16 09:08 UTC, merged