fill node info when upstream node update
apache/apisix pull request #9806
Opened 2023-07-09 13:55 UTC by ZhangShangyu

### Description

Fixes https://github.com/apache/apisix/issues/9805

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)

2023-07-10 07:13 UTC, shreemaan-abhishek commented
Could you please add test cases?

2023-07-21 03:58 UTC, ZhangShangyu commented
i have no good idea to write test about this scene, any suggestions?
btw i am stuck at setup and run test framework on my m1 macbook😂

2023-07-24 01:42 UTC, leslie-tsang commented
> i have no good idea to write test about this scene, any suggestions? btw i am stuck at setup and run test framework on my m1 macbook😂

@shreemaan-abhishek cloud please help him to add test case to this PR ? :)

2023-07-24 04:39 UTC, shreemaan-abhishek commented
@leslie-tsang I haven't repro the bug yet. Let me try to do that first.

2023-07-31 03:07 UTC, Sn0rt commented
we need test case to ensure the https://github.com/apache/apisix/issues/9805 has been fixed.

2023-08-13 14:56 UTC, shreemaan-abhishek commented
@leslie-tsang, @ZhangShangyu's point is valid and the fix looks correct to me. But I don't know how we can provide a simpler way to test this case.

The current way to implement testing would be to create a discovery plugin as proposed by the user (the plugin is for an extremely specific purpose) and then making some requests.

2023-08-14 03:21 UTC, shreemaan-abhishek commented
Github actions shows workflows are in progress even if they have completed running:
<img width="962" alt="image" src="https://github.com/apache/apisix/assets/61597896/45446782-8eeb-412f-b8b2-f63e4371c862">

I will close and re-open this PR to try to fix this issue.

2023-08-14 03:50 UTC, ZhangShangyu commented
> @leslie-tsang, @ZhangShangyu's point is valid and the fix looks correct to me. But I don't know how we can provide a simpler way to test this case.
> 
> The current way to implement testing would be to create a discovery plugin as proposed by the user (the plugin is for an extremely specific purpose) and then making some requests.

the root cause is the cache inconsistent, how about write test to verify the cache?

2023-08-14 05:11 UTC, shreemaan-abhishek commented
@ZhangShangyu, looks like your changes broke something. Please fix the CI failure:

<img width="999" alt="image" src="https://github.com/apache/apisix/assets/61597896/6f42a1f4-7d0d-4b20-baef-abcb0cfc9e06">
https://github.com/apache/apisix/actions/runs/5851484873/job/15862317840?pr=9806#step:19:515

2023-08-14 06:33 UTC, ZhangShangyu commented
> @ZhangShangyu, looks like your changes broke something. Please fix the CI failure:
> 
> <img alt="image" width="999" src="https://user-images.githubusercontent.com/61597896/260362943-6f42a1f4-7d0d-4b20-baef-abcb0cfc9e06.png"> https://github.com/apache/apisix/actions/runs/5851484873/job/15862317840?pr=9806#step:19:515

it like the config validation fail, my change seems not related to the validation, can rerun this test?
<img width="1004" alt="image" src="https://github.com/apache/apisix/assets/15957047/ad71c76c-42cc-4a0b-9496-7d8d973df29f">

2023-08-14 10:56 UTC, shreemaan-abhishek commented
@ZhangShangyu, I am convinced that your changes are producing the CI failures. The re-run also failed.

2023-08-15 08:13 UTC, ZhangShangyu commented
> @ZhangShangyu, I am convinced that your changes are producing the CI failures. The re-run also failed.

i saw this PR check job also failed, but it was fixed now, can i know how do you fix it?
https://github.com/apache/apisix/actions/runs/5857369728/job/15879091957?pr=10008

2023-08-15 16:48 UTC, shreemaan-abhishek commented
> i saw this PR check job also failed, but it was fixed now, can i know how do you fix it?

We re-run the CI. I did it for your PR as well but it didn't work.

2023-08-23 03:44 UTC, Sn0rt commented
@ZhangShangyu can you provider the permisson for cooperation with @shreemaan-abhishek

2023-08-23 03:53 UTC, ZhangShangyu commented
> @ZhangShangyu can you provider the permisson for cooperation with @shreemaan-abhishek

you mean add collaborators in my repo? if so i added just now

2023-08-24 03:54 UTC, shreemaan-abhishek commented
@ZhangShangyu you are using the service discovery feature essentially for routing, your use case is not a standard practice and the bugfix is breaking other things. Are you able to reproduce this bug using existing service discoverers?

2023-08-24 08:18 UTC, ZhangShangyu commented
> @ZhangShangyu you are using the service discovery feature essentially for routing, your use case is not a standard practice and the bugfix is breaking other things. Are you able to reproduce this bug using existing service discoverers?

hi, the point is that upstream nodes change frequently and change back like A -> B -> A,  
using existing service discoverer like Nacos or others if has this discover case it will also cause the unexpected behavior

anyway let me try to run and fix the failure tests, thx😄

2023-08-24 19:36 UTC, shreemaan-abhishek commented
> hi, the point is that upstream nodes change frequently and change back like A -> B -> A,

in the real world, it is very unlikely that the upstream nodes would change frequently like that.

2023-09-26 02:51 UTC, monkeyDluffy6017 commented
@ZhangShangyu are you still handling this issue?

2023-09-27 08:46 UTC, monkeyDluffy6017 commented
@Sn0rt It's a cache problem, please help to handle this

2023-09-27 11:32 UTC, Revolyssup commented
I have tested this PR. And it LGTM. But we will have to add tests for it using existing service discovery mechanisms.

2023-09-27 12:19 UTC, shreemaan-abhishek commented
Github action isn't allowing re-runs, closing and reopening this PR because it might fix the issue.

2023-09-27 18:54 UTC, Revolyssup commented
@ZhangShangyu Can you rebase with master?

2023-09-28 05:35 UTC, Revolyssup requested changes

2023-09-28 05:35 UTC, Revolyssup commented on apisix/upstream.lua
> +                    return 503, err
can you change this to 502? This is what's failing the test

2023-09-28 05:35 UTC, Revolyssup commented on apisix/upstream.lua
> +                    return 503, err
dittto

2023-09-28 05:35 UTC, Revolyssup commented
@ZhangShangyu If you don't have time, you can give me permissions on this branch and I can take this over.

2023-10-07 07:15 UTC, ZhangShangyu commented
> @ZhangShangyu If you don't have time, you can give me permissions on this branch and I can take this over.

ok, just in holiday, thank you

2023-10-07 09:08 UTC, ZhangShangyu commented
> @ZhangShangyu Can you rebase with master?

done

2023-10-09 03:40 UTC, monkeyDluffy6017 commented
@Revolyssup @ZhangShangyu The ci is still failing, do you guys want to keep working on this?

2023-10-10 03:35 UTC, Revolyssup commented
> @Revolyssup @ZhangShangyu The ci is still failing, do you guys want to keep working on this?

I'll take a look here and update today.

2023-10-24 06:10 UTC, ZhangShangyu commented
> > @Revolyssup @ZhangShangyu The ci is still failing, do you guys want to keep working on this?
> 
> I'll take a look here and update today.

Hi @Revolyssup, any update?

2023-10-24 06:29 UTC, Revolyssup commented
> > > @Revolyssup @ZhangShangyu The ci is still failing, do you guys want to keep working on this?
> > 
> > 
> > I'll take a look here and update today.
> 
> Hi @Revolyssup, any update?

Yeah I am looking at the changes right now. I had gotten busy with other stuff previously. Failing tests are related to changes. I will ping in case I need help

2023-12-19 06:28 UTC, sheharyaar commented
@Revolyssup , I would like to take up this PR.

2024-01-03 08:13 UTC, monkeyDluffy6017 commented
It's fixed by https://github.com/apache/apisix/pull/10722

2024-01-03 08:13 UTC, closed without merging